openapi: 3.0.3
info:
  title: Rilevatori API
  description: API for managing Impianto and Rilevatore
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: 'Local server'
paths:
  /impianto/{id}:
    get:
      summary: Get a specific Impianto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Impianto not found
  /rilevatori_di_umidita:
    get:
      summary: Get all Rilevatore of type umidita
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    post:
      summary: Create a new Rilevatore of type umidita
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                codiceSeriale:
                  type: string
                posizione:
                  type: string
                impianto_id:
                  type: integer
      responses:
        '201':
          description: Rilevatore created
        '500':
          description: Failed to create Rilevatore
  /rilevatori_di_umidita/{id}:
    get:
      summary: Get a specific Rilevatore of type umidita
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    delete:
      summary: Delete a specific Rilevatore of type umidita
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    put:
      summary: Update a specific Rilevatore of type umidita
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                posizione:
                  type: string
                impianto_id:
                  type: integer
      responses:
        '200':
          description: Rilevatore updated
        '500':
          description: Failed to update Rilevatore
  /rilevatori_di_umidita/{id}/misurazioni:
    get:
      summary: Get all Misurazione for a specific Rilevatore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: No measurements found for this detector
  /rilevatori_di_umidita/{id}/maggiore_di/{valore_minimo}:
    get:
      summary: Get all Misurazione for a specific Rilevatore with a value greater than a specified minimum
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: valore_minimo
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
        '404':
          description: No measurements found for this detector greater than specified value
  /rilevatori_di_temperatura:
    get:
      summary: Get all Rilevatore of type temperatura
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    post:
      summary: Create a new Rilevatore of type temperatura
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                codiceSeriale:
                  type: string
                posizione:
                  type: string
                impianto_id:
                  type: integer
      responses:
        '201':
          description: Rilevatore created
        '500':
          description: Failed to create Rilevatore
  /rilevatori_di_temperatura/{id}:
    get:
      summary: Get a specific Rilevatore of type temperatura
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    delete:
      summary: Delete a specific Rilevatore of type temperatura
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: Rilevatore not found
    put:
      summary: Update a specific Rilevatore of type temperatura
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                posizione:
                  type: string
                impianto_id:
                  type: integer
      responses:
        '200':
          description: Rilevatore updated
        '500':
          description: Failed to update Rilevatore
  /rilevatori_di_temperatura/{id}/misurazioni:
    get:
      summary: Get all Misurazione for a specific Rilevatore
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '404':
          description: No measurements found for this detector
  /rilevatori_di_temperatura/{id}/maggiore_di/{valore_minimo}:
    get:
      summary: Get all Misurazione for a specific Rilevatore with a value greater than a specified minimum
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: valore_minimo
          in: path
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Successful operation
        '404':
          description: No measurements found for this detector greater than specified value
